### ISSUE TITLE
selector-search.gif missing

### ISSUE THREAD

**Issue by bctiemann** [django-extensions/django-extensions#1221]
widgets/foreignkey_searchinput.html has the following:

    <img src="{% static "admin/img/selector-search.gif" %}" width="16" height="16" alt="{% trans "Lookup" %}" />

But there is no such image in the statics.

**Comment by arthurio** [comment]
It's a long time know bug (see https://github.com/django-extensions/django-extensions/issues/229 and https://github.com/django-extensions/django-extensions/issues/786).

Since at least Django 1.9 (I don't know for previous versions), the `related-lookup` class will get the image icon from the `Django` css:

```css
.related-lookup {
    width: 16px;
    height: 16px;
    background-image: url(../img/search.svg);
}
```

So I think we can simply drop the `img` tag altogether.

I'd be happy to submit a PR but I'm not sure what are the expectations in terms of compatibility with older versions of Django. Also, I'm sure we can really test the change? Maybe it's not super important since it has not been working for so long?
